### ISSUE TITLE
Sarabia et. al. Package Evaluation

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#11]
**Title:**

Face Mask and Physical Distancing Detection System Using Computer Vision

**Members:**

Hugo Leroy D. Chavez, Flora May D. Gicanal, Christian T. Sarabia, Marianne Therese E. Tunggak

**Comment by geniusqwerty12** [comment]
Started checking the user manual and tried to follow the instructions on how to run the program, so far these are the things I encountered:

User Manual:
1. Page 4, the command _pip install -r requirement.txt_, the file name should be requirements.txt.

Errors:
1. ERROR: Could not find a version that satisfies the requirement wintoast==0.9 (from versions: 0.1, 0.2) ERROR: No matching distribution found for wintoast==0.9
this is an error I encountered when trying to run the install modules/packages command. Upon checking the codes, I think you used win10toast instead of wintoast (which is currently on the requirements.txt), changing it to win10toast==0.9 solves the issue.

2. Also, the module _plyer_ was not found on the requirements.txt, please add as main.py uses it.

3. Following what the user manual, I've created the yolo-coco folder and pasted the weights, however when I tried to execute the program, an error or two was encountered
[Errno 2] No such file or directory: 'yolo-coco/coco.names'
net = cv2.dnn.readNetFromDarknet(configPath, weightsPath)
After getting it from on of the members, I was able to run the program. Please put the missing files coco.names and yolocv3.cfg in the repo, preferably inside the yolo-coco folder, so that the user will just download the weights

**Comment by Sturg25** [comment]
The mentioned concerns has been addressed;

- In the manual and the readme.md, "_pip install -r requirement.txt_" has now been change to "_pip install -r requirements.txt_" 
- In the requirements.txt, the module "_wintoast_" has now been changed to  "_win10toast_" and also appended the module "_plyer_"
- In the GitHub repository, in the _src_ folder we have added the yolo-coco folder and the files "_coco.names_" and "_yolov3.cfg_" to address the Error 3

The Manual and the Readme.md has also been edited to apply changes to the installation instructions of the project.

**Comment by geniusqwerty12** [comment]
Just confirmed that all of the concerns have been addressed on the repository. @Sturg25 let me know if you can or can't create the exe file.

**Comment by geniusqwerty12** [comment]
Passing this to @cictapps @mjsolidarios @regincabacas for approval
