### ISSUE TITLE
Carabaño et. al. Package Evaluation

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#23]
**Title:**
Mango Grading for Product Suitability Recommendation Using Computer Vision

**Members:**
Julia S. Carabaño, Jessa Mae F. Nopueto, Theodore Walter T. Galve, Jonah James A. Pormento

**Comment by geniusqwerty12** [comment]
Here are my feedbacks for 
1. USER MANUAL:
a. all the sections of the user manual are present with respect to the guidelines.
b. in the installation phase, please put the github link of the source codes/project (https://github.com/jjpormento21/project_mango/tree/main/src), I noticed there is no link for the user to access in order to download/clone the project. You can add this as the first step
c. Fix spelling error on Installation section: Perequisites to Prerequisites.

**Comment by jjpormento21** [comment]
Thank you for your feedback sir @geniusqwerty12 
Implemented revisions via this commit: https://github.com/jjpormento21/project_mango/commit/ba1cd1b73af3142f5c4c074dc086349b070d23a2

Changelog:
- Added first step in Installation phase on the user manual that tells the user to clone the repository.
- Fixed typo on page 5.

Files changed:
[User Manual.pub](https://github.com/jjpormento21/project_mango/blob/main/doc/User%20Manual%20-%20Project%20Mango.pub)
[User Manual PDF](https://github.com/jjpormento21/project_mango/blob/main/doc/User%20Manual%20-%20Project%20Mango.pdf)

**Comment by geniusqwerty12** [comment]
Good afternoon @jjpormento21 , all of the changes requested are present on the document, with regards to the source code, all is working well. Closing this issue once their manuscript is finished on the final checking. @cictapps @regincabacas

**Comment by geniusqwerty12** [comment]
Changing status for certification. @jjpormento21 please update the repo if the manuscript is already finalized. We can process your certification in advance. @cictapps

**Comment by jjpormento21** [comment]
Thank you sirs @geniusqwerty12 and @cictapps for checking. God bless!
