### ISSUE TITLE
Carbonilla et. al. Package Evaluation

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#27]
**Title:**
Syrene: Chatbot Assisting Mental Health Professionals in Dealing with Patients/Clients Using Machine Learning

**Members:**
Gene Caleb C. Carbonilla, Xyphrus Von Keith V. Caguan, Jirah Kate C. Solano, Joshreen D. Reyes

**Comment by geniusqwerty12** [comment]
Checked the project (client, admin and server) and tried the functionalities of the system, all is working with little to no issues.

As for the user manual, here are my feedbacks:
1. On the  System requirements section,  add the software needed to run the system, so far, I installed:
	node
	python
	visual studio code

2. Installation Step 2, missing venv activate, and instead of running the command stated on the manual, you can just run: pip install -r requirements.txt
3. Installation on the client and admin, please clarify the steps for each app.

4. Follow up the missing sections
	(Troubleshooting, FAQs, Contact Details and Back cover).

5. Please put the server, client and admin on the server on a folder called "src" as stated on the thesis package template for web apps. Once done, update the steps that navigates the user to each directory on the manual.

@cictapps

**Comment by joshierin** [comment]
Hi Sir @geniusqwerty12 . Good evening. Thank you for the feedback.

Have already implemented revisions in the user manual:

1. Already added the software needed to run the system in the _"System Requirements"_
2. Added line of command in 1st step of _"Installation"_ in order to activate the virtual environment
```
$ . venv/Scripts/activate
```
and have changed the line of command in the 2nd step to:
```
$ (venv) pip install –r requirements.txt
```
3. Have already clarified the steps of each app for the installation of client and admin.
4. Already had a little bit of design/content in the back cover.
5. Had created src folder and put the server, admin and client inside the folder. Lastly, have already updated the steps that navigates the user to each directory on the manual.

Uploaded both .pub and .pdf of the user manual. Thank you!

**Comment by geniusqwerty12** [comment]
All of the changes above are present in the manuscript.
One minor issue on the Deployment section, before running the command "npm start", please include the command "npm install" for installing the npm dependencies.
![image](https://github.com/wvsu-cict-code/thesis-package/assets/81214610/17c6d0c9-07e7-4b38-b628-ce764b744b93)

**Comment by joshierin** [comment]
Hello Sir @geniusqwerty12.

We have added the "INSTALLATION OF DEPENDENCIES IN FRONTEND" before the _"DEPLOYMENT OF FRONTEND_ section and added a line of command of:
```
npm install
```

Thank you!

**Comment by geniusqwerty12** [comment]
Good day @joshierin, the changes are present in the user manual. Please upload the soft copy of your manuscript once it is ready for hardbinding.
@cictapps changing the status to for certification to process their certificate in advance.

**Comment by joshierin** [comment]
Thank you Sirs @geniusqwerty12 and @cictapps for checking and certifying our thesis package. God bless!

**Comment by cictapps** [comment]
We have sent the completion certificate. Congratulations!
