### ISSUE TITLE
Felasol et. al. Package Certification

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#45]
**Title:** 
HealthSense: A medical device with an embedded sensor system for vital signs monitoring and Heart Disease prediction.

**Members:**
Ana Patricia F. Felasol, Thrys J. Formoso, Patricia Anne A. Gaquit, John Kate E. Marbebe, Luke Ian B. Undar

**Comment by geniusqwerty12** [comment]
User Manual:
1. Running the web application
  provide instructions on how to run the web application

2. Microcontroller and module setup
  include the diagram of the setup for your microcontroller

3. What does the "Feeling/Feel Anything" button in the application trigger/lead to? 


Thesis package github:
1) Image assets
  please use the proper assets (specifically for the app icon)
  The assets included here are supposed to be the screenshots of the mobile application
![image](https://github.com/wvsu-cict-code/thesis-package/assets/81214610/313707f0-2f65-4f5e-80e0-ee5130993245)


2) source code of the mobile application
  please include the source codes used in order to create the mobile application
  (you can create another folder called mobile_app and store the source code there)

**Comment by DarthFrost2** [comment]
Sir, Good Evening. We have made changes according to your corrections. Thank you for your time.

**Comment by geniusqwerty12** [comment]
Good day @DarthFrost2, all of the feedback have been implemented in the repository.
One last thing is the order of section in the User Manual, in the order below
![image](https://github.com/wvsu-cict-code/thesis-package/assets/81214610/5b225405-c5c4-4fd4-bb77-f10688105a41)
Requirements
Setup
Installation
Usage per feature

**Comment by DarthFrost2** [comment]
We have implemented the changes based on your corrections. Thank you, Sir.

**Comment by geniusqwerty12** [comment]
Good day @DarthFrost2! Did you change the order of the sections? Because the location of the Web App guide should be in the Usage per Feature, as well as the Setup and Usage of the IoT, the SETUP and USAGE are separate components.

**Comment by Pidodida** [comment]
Good afternoon sir @geniusqwerty12, changes have been made...

**Comment by geniusqwerty12** [comment]
Good day @DarthFrost2 @Pidodida the changes made on the document satisfies the format given. Passing this to sir @mjsolidarios for your cerfication.

**Comment by DarthFrost2** [comment]
Good Afternoon Sir @geniusqwerty12 Thank you for your valuable assistance to our group. We appreciate your time and expertise in reviewing our User Manual.
