### ISSUE TITLE
Arroyo et. al. Package Certification

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#58]
**Title:**
Unhealthy Swine Detector

**Members:**
Karen H. Arroyo
Ellan V. Flores
Mary Ruth N. Lusuegro
Rey Matthew G. Parreño
Aldrex Mark B. Tingatinga

**Comment by geniusqwerty12** [comment]
Good morning @aldrexmark, for the user manual, items 1-4 were addressed in the current repository. 
Here are a list of comments that needs to be addressed:
1. Since this part here is part of your application, put that in the Usage section
![image](https://github.com/user-attachments/assets/935664fe-292b-4fb6-a681-bf29eb6bf496)

2. Put the output page as part of the feature (Usage section)

Regarding your source code, please address the following issues
1. When check the source code for the configuration of the database, the directories related for MySQLite are absolute, i.e.
![image](https://github.com/user-attachments/assets/c291f7c6-0452-4ec3-ad0e-a44e763e1924)

2. please put the image folders inside the src, since they are technically part of the source codes
3. put mysetup.exe inside the dist folder

**Comment by aldrexmark** [comment]
Good day sir @geniusqwerty12 , changes have been made in our repo. Thank you!!!

**Comment by aldrexmark** [comment]
Good day Sir @geniusqwerty12, changes have been made in our repo. Thank you!!!

**Comment by geniusqwerty12** [comment]
Good day @aldrexmark, 2 of the feedback were addressed in the repository. Thank you!
Sir @mjsolidarios moving this issue to for certification.

**Comment by aldrexmark** [comment]
thank you for the help sir!
