### ISSUE TITLE
Duran et. al. Package Evaluation

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#9]
Title:

Project Ahon: An agile tracking system using mobile embedded systems for COVID-19 tracking

Members:

Joseph Anthony Duran, Horacio Jason Barba V, Jovan Earl Hinayan, Carlo Adrian Reyes

**Comment by geniusqwerty12** [comment]
Please follow the github repo structure as seen in this link: https://github.com/wvsu-cict-code/thesis-package/tree/master/web_app_games/web_app_or_game_name

With regards on the User Manual passed via Email, here is my feedback:
1. Images are clear, I can follow most of the instructions, but some I cannot because of the missing hardware.

2. Please create another page for the Title page, that will come after the Cover page.

3. This subsection right should be under the **Installation**.
![image](https://user-images.githubusercontent.com/81214610/161717649-cfcc8c4c-4360-43dd-b457-72de4a476e61.png)

Please move the **Introduction** below to the first subsection of Getting Started, as this was the correct order on the User Manual Guidelines, here: https://github.com/wvsu-cict-code/thesis-package/blob/master/MANUAL.md.

**Comment by geniusqwerty12** [comment]
Checked the new structure of the github repo, it is now okay. You've also updated the user manual, and I don't see any errors anymore. However, for the thesis manuscript, I am seeing some errors:

![image](https://user-images.githubusercontent.com/81214610/162130686-2a0a78b2-ddcf-451f-b225-ecc0d3407e11.png)

![image](https://user-images.githubusercontent.com/81214610/162130757-521e505b-463f-45ec-9ec3-cc0093388859.png)

![image](https://user-images.githubusercontent.com/81214610/162130838-13be0e61-f36a-40ff-99b5-76c478e606b6.png)

For me, the only thing that needs to be updated is the thesis manuscript. Please finalize and upload the thesis manuscript as a pdf file.

**Comment by geniusqwerty12** [comment]
I found 2 tables on the System Evaluation Results that were empty.
Here is one of them.
![image](https://user-images.githubusercontent.com/81214610/162186529-47d40e48-797c-46e6-80c0-040202689b1e.png)
